### ISSUE TITLE
Maximum 12 charac to pseudo

### ISSUE THREAD

**Issue by ycurbill** [42Flowers/transcendence#166]

**Comment by ChaDutel** [comment]
<img width="1440" alt="Capture d’écran 2023-12-09 à 21 01 16" src="https://github.com/42Flowers/transcendence/assets/87937434/3827fb36-2d84-4b19-b659-aa9eae591c8f">

**Comment by Hloise** [comment]
Fait sur une autre issue plus récente: mais par contre ça a été limité à 10
