### ISSUE TITLE
back max characters

### ISSUE THREAD

**Issue by ChaDutel** [42Flowers/transcendence#184]
- max 100 characters for input msg in chat
- max 10 characters for channels and user names
- max 20 for password channels (and password auth?)

**Comment by Hloise** [comment]
Je les ai tous limités, même dans l'auth

**Comment by ChaDutel** [comment]
<img width="1440" alt="Capture d’écran 2023-12-10 à 13 49 28" src="https://github.com/42Flowers/transcendence/assets/87937434/6414f84a-964d-433a-921c-fcc40ae7321c">

Top!
du coup mettre à jour le message d'erreur (10 au lieu de 32 du coup?)
